name: Run Cypress tests

on:
  workflow_run:
    workflows: ["Deploy dev to AWS"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: 16.x

      - run: |
          touch .env
          echo VITE_APP_CLIENT_ID=${{secrets.VITE_APP_CLIENT_ID}} >> .env
          echo VITE_APP_API_URL=${{secrets.VITE_APP_API_URL}} >> .env
          echo VITE_APP_CLIENT_URL=https://tutorial.eaglesoftwareteam.com >> .env
          echo VITE_APP_CLIENT_SECRET=${{secrets.VITE_APP_CLIENT_SECRET}} >> .env
          echo VITE_APP_REFRESH_TOKEN=${{secrets.VITE_APP_REFRESH_TOKEN}} >> .env

      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          VITE_APP_CLIENT_ID: ${{secrets.VITE_APP_CLIENT_ID}}
          VITE_APP_API_URL: ${{secrets.VITE_APP_API_URL}}
          VITE_APP_CLIENT_URL: https://tutorial.eaglesoftwareteam.com
          VITE_APP_CLIENT_SECRET: ${{secrets.VITE_APP_CLIENT_SECRET}}
          VITE_APP_REFRESH_TOKEN: ${{secrets.VITE_APP_REFRESH_TOKEN}}
        with:
          build: npx cypress info
          config: baseUrl=https://tutorial.eaglesoftwareteam.com/tutorial-frontend-vue3
          headed: true
